repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # удаляет пробелы в конце строк
      - id: end-of-file-fixer    # гарантирует одну пустую строку в конце файла
      - id: check-yaml           # проверяет синтаксис YAML
      - id: check-added-large-files  # блокирует случайный коммит больших файлов

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=79]  # как у PEP 8

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]  # совместимость с black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=79, --ignore=E203,W503]
