#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'cmd-to-high-level-control-package','console_scripts','cmd_to_high_level_control_node'
__requires__ = 'cmd-to-high-level-control-package'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('cmd-to-high-level-control-package', 'console_scripts', 'cmd_to_high_level_control_node')()
    )
