#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'low-level-control','console_scripts','hands_node_with_lib'
__requires__ = 'low-level-control'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('low-level-control', 'console_scripts', 'hands_node_with_lib')()
    )
